// public class GenerateBill {

//     public static void main(String[] args) {

//     }
// }

// package home;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.GridLayout;
import java.awt.Image;
// import java.awt.event.ActionEvent;
// import java.awt.event.ActionListener;

import javax.swing.*;
// import javax.swing.border.Border;

public class GenerateBill extends JFrame {
    private int num;
    private int capacity;
    // private JTextField jTextField_qty;
    private JPanel panel1;
    private JPanel panel11;
    private JPanel panel11Left;
    private JLabel ansJLabel;
    private Validation obj;
    private KnapSackFractional knapFra;
    private boolean flag;
    private boolean checkFractinal[];
    // private JLabel count;
    // private JLabel pname;
    // private JLabel pweight;
    // private JLabel pprofit;
    // private JLabel fractional;
    private JLabel array[];
    // private JCheckBox checkBoxs[];
    // private JMenu menus[];
    private JLabel rbtns[];

    public GenerateBill(int num, int capacity, String invoiceDetail[][],double ans) {
        String textFields[] = new String[num];
        this.num = num;
        this.capacity = capacity;
        obj = new Validation();
        System.out.println(textFields.length);
        // JLabel jlabel1=new JLabel();
        // setLocation(100, 50);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ImageIcon homeImage = new ImageIcon("back.jpeg");
        setIconImage(homeImage.getImage());
        Image i2 = homeImage.getImage().getScaledInstance(1920, 1080, Image.SCALE_DEFAULT);
        ImageIcon i3 = new ImageIcon(i2);
        JLabel image = new JLabel(i3);
        // image.setBounds(0, 0,1200 , 800);
        // add(image);
        // TODO: Panel 11 info =data=================
        panel11 = new JPanel();
        panel11.setBounds(250, 50, 1000, 90);
        panel11.setLayout(null);
        panel11.setBackground(Color.black);
        JLabel head = new JLabel("Welcome to Bharat Transportation");
        head.setForeground(Color.WHITE);
        head.setFont(new java.awt.Font("Segoe UI", 1, 24));
        head.setBounds(300, 0, 500, 50);
        add(panel11);
        // TODO: Line Pannel=============
        JPanel line1 = new JPanel();
        line1.setBounds(0, 45, 1000, 5);
        panel11.add(line1);
        //
        JLabel heading_item = new JLabel("Total Bill Generated by Bot ");
        heading_item.setForeground(Color.WHITE);
        heading_item.setFont(new java.awt.Font("Segoe UI", 1, 20));
        heading_item.setBounds(300, 50, 500, 40);
        panel11.add(head);
        panel11.add(heading_item);
        // TODO: Left Top panel -1 =======
        JPanel leftTop = new JPanel();
        leftTop.setBounds(250, 140, 100, 40);
        leftTop.setBackground(Color.blue);
        JLabel srnLabel = new JLabel("S. No ");
        // srnLabel.setBounds(250,190,100,40);
        srnLabel.setFont(new java.awt.Font("Segoe UI", 1, 18));
        srnLabel.setForeground(Color.white);
        srnLabel.setAlignmentY(45);
        ;
        add(leftTop);
        leftTop.add(srnLabel);
        // TODO panel 1 -left side============
        panel11Left = new JPanel();
        panel11Left.setBounds(250, 180, 100, 450);
        panel11Left.setLayout(null);
        panel11Left.setBackground(Color.black);

        JPanel line2 = new JPanel();
        line2.setBounds(0, 45, 100, 5);
        JLabel[] labels = new JLabel[num];
        for (int i = 0; i < num; i++) {
            labels[i] = new JLabel("    " + (i + 1) + ".");
            labels[i].setAlignmentY(CENTER_ALIGNMENT);
            labels[i].setForeground(Color.WHITE);
            labels[i].setFont(new java.awt.Font("Segoe UI", 1, 18));
            panel11Left.add(labels[i]);
        }
        add(panel11Left);
        // panel11Left.add(line2);
        panel11Left.setLayout(new GridLayout(0, 1));
        panel11Left.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        // TODO: Panel -1 upper part===
        JPanel upperPart = new JPanel();
        upperPart.setBounds(350, 140, 900, 40);
        upperPart.setLayout(null);
        upperPart.setBackground(Color.blue);
        add(upperPart);
        upperPart.setLayout(new GridLayout(0, 4));
        String content[] = { "Product Name", "Weight", "Profit", "Fractional" };
        JLabel[] conlabels = new JLabel[4];
        for (int i = 0; i < 4; i++) {
            conlabels[i] = new JLabel("     " + content[i]);
            // conlabels[i].setBounds(860, 125, 200, 50);
            conlabels[i].setForeground(Color.WHITE);
            conlabels[i].setFont(new java.awt.Font("Segoe UI", 1, 18));
            upperPart.add(conlabels[i]);

        }

        // TODO: Panel - 1 info=======
        panel1 = new JPanel();
        panel1.setBounds(350, 180, 650, 450);
        panel1.setLayout(null);
        panel1.setBackground(Color.black);
        add(panel1);
        panel1.setLayout(new GridLayout(0, 3, 0, 3));
        array = new JLabel[3 * num];
        // for (int i = 0; i < 3 * num; i++) {

        // }
        int indexforx = 0;
        for (int i = 0; i < 3 * num; i++) {

            for (int j = 0; j < 3; j++) {
                array[i] = new JLabel(invoiceDetail[indexforx][j]);
                array[i].setFont(new java.awt.Font("Segoe UI", 1, 16));
                array[i].setForeground(Color.white);
                panel1.add(array[i]);
                // System.out.println("Hello : "+invoiceDetail[indexforx][j]);
                System.out.println("Value of i= " + i + " val of x= " + indexforx + " val of j= " + j);
                // array[i].setText(invoiceDetail[indexforx][j]);
                System.out.println("data: => " + invoiceDetail[indexforx][j]);
                // if(j==2){
                // indexforx++;

                // }
            }
            indexforx++;
            if (indexforx >= invoiceDetail.length)
                break;

        }
        // for(int i=0;i<invoiceDetail.length;i++){
        // for(int j=0;j<3;j++){
        // System.out.println("Hello : "+invoiceDetail[i][j]);
        // array[i].setText(invoiceDetail[i][j]);
        // }
        // }
        // panel1.setBorder(BorderFacto)

        // TODO: Panel -1 right part having fractional=======
        JPanel rightJPanel = new JPanel();
        rightJPanel.setBounds(1000, 180, 250, 450);
        rightJPanel.setBackground(Color.black);
        add(rightJPanel);
        rightJPanel.setLayout(new GridLayout(0, 1, 0, 3));

        // checkBoxs=new JCheckBox[num];
        // menus=new JMenu[num];
        rbtns = new JLabel[num];
        for (int i = 0; i < num; i++) {
            rbtns[i] = new JLabel("          Yes");
            rbtns[i].setFont(new java.awt.Font("Segoe UI", 1, 16));
            rbtns[i].setForeground(Color.WHITE);
            rightJPanel.add(rbtns[i]);

        }
        // TODO: === Components of Panel 1=============

        JPanel line11 = new JPanel();
        line11.setBounds(0, 55, 1000, 8);
        // TODO: Last label and submit btn=========
        JPanel lastJPanel = new JPanel();
        lastJPanel.setBounds(250, 630, 1000, 40);
        JLabel findJLabel = new JLabel("Caculate the Maximum Profit : ");
        findJLabel.setFont(new java.awt.Font("Segoe UI", 1, 20));
        findJLabel.setBounds(0, 0, 300, 40);
        lastJPanel.setBackground(Color.black);
        findJLabel.setForeground(Color.white);
        ansJLabel = new JLabel("₹ "+ans);
        ansJLabel.setFont(new java.awt.Font("Segoe UI", 1, 20));
        ansJLabel.setForeground(Color.ORANGE);
        JButton backBtn = new JButton("<-- Back");
        backBtn.setBounds(600, 670, 300, 45);
        backBtn.setBackground(Color.blue);
        backBtn.setForeground(Color.white);
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 18));
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMargin(new java.awt.Insets(2, 17, 3, 17));
        // add(SubmitBtn);
        backBtn.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                jButton1ActionPerformed(evt);
            }
        });
        add(lastJPanel);
        lastJPanel.add(backBtn);
        lastJPanel.add(findJLabel);
        lastJPanel.add(ansJLabel);
        add(backBtn);
        JPanel panel2 = new JPanel();
        panel2.add(image);
        add(panel2);

    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // System.exit(0);
        setVisible(false);
        doLayout();

        // // TODO add your handling code here:
    }

    private void fillData(String totalString[], String pname[], int pweight[], int profit[], int qty) {

    }

    public static void main(String[] args) {
        String s[][] = new String[1][2];
        GenerateBill ob = new GenerateBill(10, 6, s,89.89);
        ob.setSize(1920, 1080);
        // ob.setLayout(null);
        ob.setVisible(true);
        // String a="aman";

    }
}
